# Standardkonfiguration f端r das Integrierte System

data:
  raw_path: "data/raw/"
  processed_path: "data/processed/"
  dimensions: 6  # Kann zwischen 1 und 6 angepasst werden
  sensor_features: ["x", "y", "z", "roll", "pitch", "yaw"]
  sensor_units:
    x: "m"
    y: "m"
    z: "m"
    roll: "deg"
    pitch: "deg"
    yaw: "deg"

model:
  contamination: 0.05
  random_state: 42
  n_estimators: 100
  save_path: "data/models/model.pkl"

preprocessing:
  normalization: true
  resample_rate: "1S"

# Konfiguration zur GSV Integration (Beispielwerte)
gsv:
  port: 5000
  baud_rate: 9600
  device_id: "GSV-001"

api:
  host: "0.0.0.0"
  port: 8000
  cors_origins: ["*"]          # Neue: CORS-Konfiguration f端r die API
  auth:
    enabled: false             # Neue: API-Authentifizierung aktivieren/deaktivieren
    token: "geheimer_token"    # Platzhalter f端r einen API-Schl端ssel

logging:
  level: "INFO"                # Neue: Log-Level (DEBUG, INFO, WARN, ERROR)
  file: "logs/integrated_system.log"  # Pfad zur Log-Datei

database:
  default:
    url: "sqlite:///feedback.db"   # Neue: Standard-Datenbankverbindung
  postgres:                       # Optional: Weitere Datenbankkonfigurationen
    url: "postgresql://user:pass@localhost:5432/dbname"

kafka:
  bootstrap_servers: ["localhost:9092"]   # Neue: Kafka-Verbindungsdetails
  topics:
    input: "sensor_input"
    feedback: "feedback_topic"
